### ISSUE TITLE
No Subject in Email Messages.

### ISSUE THREAD

**Issue by alexhiggins732** [zabszk/CSharp-SMTP-Server#1]
The `IMessageTransaction` interface and implementations do not implement `Subject` and the underlying server code does not parse the subject of the email.

**Comment by zabszk** [comment]
Sorry for the delay. Mail Subject is just a header and technically it's rather for mail client, not SMTP server. However I'm working on email headers parsing.

**Comment by zabszk** [comment]
Released in version 1.1.0.
