### ISSUE TITLE
Auth LOGIN: Error 

### ISSUE THREAD

**Issue by frankyjquintero** [zabszk/CSharp-SMTP-Server#12]
LOGIN authentication must be set in some scenarios the login argument sends user at the same time

https://github.com/zabszk/CSharp-SMTP-Server/blob/c23f9adae7859ab7aa310b0973d6d222e7a77219/CSharp-SMTP-Server/Protocol/Commands/AuthenticationCommands.cs#L25-L38

![image](https://github.com/zabszk/CSharp-SMTP-Server/assets/22311691/053d592d-402c-4f0c-ba3d-36109254ef6f)

![image](https://github.com/zabszk/CSharp-SMTP-Server/assets/22311691/50e1a793-13df-430a-9966-be34e91b8384)

**Comment by zabszk** [comment]
Hi,

Sorry for a very delayed response. AUTH LOGIN is defined by this document: https://www.ietf.org/archive/id/draft-murchison-sasl-login-00.txt (in general this method is obsolete and was never an official standard: https://www.iana.org/assignments/sasl-mechanisms/sasl-mechanisms.xhtml).

The standard doesn't define a possibility to send username in the same line as `AUTH LOGIN` command. In general `AUTH PLAIN` should be used instead - it's the recommended (not obsolete) method and it supports passing username and password as an argument.
