### ISSUE TITLE
Email messages missing attachments.

### ISSUE THREAD

**Issue by alexhiggins732** [zabszk/CSharp-SMTP-Server#4]
The `IMessageTransaction` interface and implementations do not implement an `Attachment` collection and the underlying server code does not parse the attachments of the email.

**Comment by ESEricWare** [comment]
I used MimeKit and this worked for me

var message = new MimeMessage();
byte[] byteArray = Encoding.ASCII.GetBytes("MailRawBody");
MemoryStream stream = new MemoryStream(byteArray);
message = MimeMessage.Load(stream);

in the resulting message all attachments are included

**Comment by zabszk** [comment]
Hi,

I have been testing MimeKit recently and it should work fine. In the future I plan to use it in this project.

**Comment by zabszk** [comment]
Feature has been implemented in the version 1.1.6, which has just been released.
