### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by ESEricWare** [zabszk/CSharp-SMTP-Server#6]
Hi everyone,

I'm trying to use this library in a docker container on Linux.

the library is starting successful but when it comes to receive a mail it's throwing this exception:

[Client receive loop] Exception: System.IndexOutOfRangeException, Index was outside the bounds of the array.

Any Idea?

Thanks in advance

**Comment by ESEricWare** [comment]
Found a solution:

EMailParser.cs in line 37

I changed

`if (!char.IsWhiteSpace(split[j][0]) || string.IsNullOrWhiteSpace(split[j]))`

against

`if (string.IsNullOrWhiteSpace(split[j]) || !char.IsWhiteSpace(split[j][0]))`

**Comment by zabszk** [comment]
Hi,

Thanks for reporting the issue. I will apply your fix in a second.

**Comment by zabszk** [comment]
Issue fixed in version 1.1.5.
