### ISSUE TITLE
[Client receive loop] Exception: System.ArgumentOutOfRangeException, Length cannot be less than zero. (Parameter 'length')

### ISSUE THREAD

**Issue by XB-RS** [zabszk/CSharp-SMTP-Server#8]
**Issue Description:**
When our application is receiving an email from an Exchange Server, it throws the following exception:

```
[Client receive loop] Exception: System.ArgumentOutOfRangeException, Length cannot be less than zero. (Parameter 'length').
```

This issue persists even if the SPF check is disabled. Unfortunately, we do not have more detailed information at this time, and it appears to be related to SPF checks or email handling. 

**Steps to Reproduce:**
1. Receive an email from an Exchange Server.
2. Observe the application's behavior.

**Expected Behavior:**
The application should handle incoming emails from the Exchange Server without any exceptions.

**Actual Behavior:**
The application throws a `System.ArgumentOutOfRangeException` exception with the message "Length cannot be less than zero."

**Additional Information:**
- The issue appears to be related to SPF checks or email handling, but more specific information about the cause of the problem is not available.
- This issue might be related to the specific content or structure of emails received from the Exchange Server, but we need assistance in diagnosing and resolving it.

**Environment:**
- Application version: 1.1.5
- Operating System: Linux and Windows
- .NET Framework version: net7.0

**Steps Taken to Resolve:**
- We have already disabled SPF checks to see if it resolves the issue, but it persists.
- Reviewed logs and code for potential issues, but the root cause is unclear.

**Comment by zabszk** [comment]
Issue has been fixed in the version 1.1.6, which has just been released.
